# Generated by Django 4.2.1 on 2023-07-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_slug'),
        ('photos', '0002_create_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tagged_pets',
            field=models.ManyToManyField(blank=True, to='pets.pet'),
        ),
    ]
